export const filter = {
  "text": "gakkou's new house\"",
  "approved": [
    null
  ],
  "types": [
    "TV",
    "Movie",
    "Music",
    "OVA",
    "Special",
    "TV Special",
    "PV",
    null
  ],
  "sources": [
    "Original",
    "Manga",
    "Unknown",
    "Game",
    "Other",
    "Light novel",
    "Visual novel",
    "Web manga",
    "Novel",
    "Web novel",
    "4-koma manga",
    "Picture book",
    "Music",
    "Mixed media",
    "Book",
    "Card game",
    "Radio"
  ],
  "airing": [
    null,
    true,
    false
  ],
  "seasons": [
    null,
    "spring",
    "fall",
    "winter",
    "summer"
  ],
  "years": [
    null,
    2025,
    2024,
    2017,
    2026,
    2021,
    2022,
    2019,
    2013,
    2006,
    2012,
    2009,
    2008,
    2004,
    2005,
    2001,
    1999,
    1998,
    2000,
    1995,
    1996,
    1989,
    1983,
    1981,
    1990,
    1977,
    1979,
    1974,
    1975,
    2027,
    1970,
    1967,
    1971,
    1968,
    1966,
    1964,
    1962
  ],
  "genres": [
    "Comedy",
    "Fantasy",
    "Adventure",
    "Sci-Fi",
    "Drama",
    "Romance",
    "Hentai",
    "Supernatural",
    "Slice of Life",
    "Avant Garde",
    "Mystery",
    "Sports",
    "Ecchi",
    "Horror",
    "Suspense",
    "Award Winning",
    "Gourmet",
    "Boys Love",
    "Girls Love",
    "Erotica",
    "Action",
    "-hentai"
  ],
  "themes": [
    "Music",
    "School",
    "Historical",
    "Anthropomorphic",
    "Mecha",
    "Parody",
    "Adult Cast",
    "Martial Arts",
    "Military",
    "Super Power",
    "Space",
    "Mythology",
    "Harem",
    "Isekai",
    "Psychological",
    "Idols (Female)",
    "Mahou Shoujo",
    "Educational",
    "Strategy Game",
    "Team Sports",
    "Gag Humor",
    "CGDCT",
    "Detective",
    "Samurai",
    "Workplace",
    "Urban Fantasy",
    "Racing",
    "Iyashikei",
    "Video Game",
    "Vampire",
    "Reincarnation",
    "Time Travel",
    "Idols (Male)",
    "Performing Arts",
    "Pets",
    "Organized Crime",
    "Love Polygon",
    "Otaku Culture",
    "Combat Sports",
    "Visual Arts",
    "Reverse Harem",
    "Survival",
    "Delinquents",
    "Childcare",
    "Crossdressing",
    "High Stakes Game",
    "Medical",
    "Love Status Quo",
    "Magical Sex Shift",
    "Villainess"
  ],
  "rating": [
    "PG-13 - Teens 13 or older",
    "G - All Ages",
    "PG - Children",
    "R - 17+ (violence & profanity)",
    "Rx - Hentai",
    "R+ - Mild Nudity",
    null
  ],
  "previousPageIndex": 0,
  "length": 133,
  "limit": 100,
  "page": 0
}